### ISSUE TITLE
Snap Points

### ISSUE THREAD

**Issue by RolePlayerVintage** [probablykory/valheim-mods#3]
Can you add snap points to the corners of the chest?

**Comment by probablykory** [comment]
I modelled the bronze chest after Valheim's chests, so that it would look and behave in a way that fits into vanilla, and none of those chests have snap points.  Are there other mods that add snap points to the vanilla chests?  I'm open to discussion, but right now I'm not convinced snap points are needed.

**Comment by RolePlayerVintage** [comment]
sorry for late response, don't hop on here often. Yeah a few mods do. it makes placement significantly easier if you aren't worried about cramming. 
'chestsnap' by frogger on Thunderstore is the best example since that's the brevity of it's features.

**Comment by probablykory** [comment]
All good, thanks for the reply.

I'll take a look at the other mods, and see if there's something easy that can be done.  If I need to rework the chest asset in unity, I might not get to it for a while.
