### ISSUE TITLE
stone ring and leather cord can't be worn at the same time?

### ISSUE THREAD

**Issue by Galvenox** [probablykory/valheim-mods#6]
issue is that they can technically be worn together, but when I put utility gems on them, some of them become inactive for some reason. not sure if it's supposed to work that way... the text for some sockets says Inactive: Other utility equipped
if you want some more info let me know

**Comment by Galvenox** [comment]
oh also when I equip leather cord the buff I get says Lumberjacking for some reason. the description of it is: Your axe counts as a tool, instead of a weapon. It deals greatly reduced damage to creatures.
although that's probably to do with Lumberjacking mod by Smoothbrain, but still a weird interaction

**Comment by probablykory** [comment]
Hi, thanks for using my mod.

> issue is that they can technically be worn together, but when I put utility gems on them, some of them become inactive for some reason. not sure if it's supposed to work that way... the text for some sockets says Inactive: Other utility equipped if you want some more info let me know

So I know this is confusing, but it is the default behavior in Jewelcrafting of a feature called Split Sockets.  It ostensibly tallies all your utility gems together and only enables the maximum per item number of gems, which by default is 3.  You can turn off Split Sockets, and it will let you wear as many utility gems as you want.

Smoothbrain's reasoning for that feature is it can be very overpowered, having 9+ utility gems available to you.

> oh also when I equip leather cord the buff I get says Lumberjacking for some reason. the description of it is: Your axe counts as a tool, instead of a weapon. It deals greatly reduced damage to creatures. although that's probably to do with Lumberjacking mod by Smoothbrain, but still a weird interaction

This is also the default intended behavior of that buff, which is also from Jewelcrafting.  It reclassifies your axe as a Tool rather than a Weapon, so when you gem it up with, for example, black gems, it gives Frenzy instead of Shadow Hit.  To compensate for the benefit it gives for chopping wood, it lowers the damage when attacking monsters.

If you'd prefer a different effect on the necklace, you can go into the MoreJewelry settings in config manager and enable External YAML, and edit that necklace to have a different buff (either one of the named buffs, or a custom adhoc effect).  Examples of what you can do are in the [default yaml](https://github.com/probablykory/valheim-mods/blob/main/MoreJewelry/Configs/MoreJewelry.defaults.yml).
